# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retriever.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'retriever.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fretriever.proto\x12\x06protos\"i\n\x0fRetrieveRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65nse_top_k\x18\x02 \x01(\x05\x12\x14\n\x0csparse_top_k\x18\x03 \x01(\x05\x12\r\n\x05top_k\x18\x04 \x01(\x05\x12\r\n\x05top_n\x18\x05 \x01(\x05\"4\n\x10RetrieveResponse\x12\x10\n\x08\x62ook_ids\x18\x01 \x03(\t\x12\x0e\n\x06scores\x18\x02 \x03(\x02\x32T\n\x13HybridBookRetriever\x12=\n\x08Retrieve\x12\x17.protos.RetrieveRequest\x1a\x18.protos.RetrieveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retriever_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVEREQUEST']._serialized_start=27
  _globals['_RETRIEVEREQUEST']._serialized_end=132
  _globals['_RETRIEVERESPONSE']._serialized_start=134
  _globals['_RETRIEVERESPONSE']._serialized_end=186
  _globals['_HYBRIDBOOKRETRIEVER']._serialized_start=188
  _globals['_HYBRIDBOOKRETRIEVER']._serialized_end=272
# @@protoc_insertion_point(module_scope)
